# Generated by Django 5.1.4 on 2025-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Social', 'Social'), ('Sports', 'Sports'), ('Foods', 'Foods'), ('Festivals', 'Festivals'), ('Outdoor', 'Outdoor')], default='Social', max_length=100),
        ),
    ]
