# Generated by Django 5.1.4 on 2025-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Social', 'Social'), ('Sports', 'Sports'), ('Foods', 'Foods'), ('Festivals', 'Festivals'), ('Outdoor', 'Outdoor'), ('Other', 'Other')], default='Social', max_length=100),
        ),
    ]
