# Generated by Django 5.1.4 on 2025-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], default='indoor', max_length=20),
        ),
    ]
