# Generated by Django 5.1.4 on 2025-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main_app/static/uploads/default.jpg', upload_to='main_app/static/uploads/'),
        ),
    ]
