# Generated by Django 5.1.4 on 2025-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main_app/static/ava/default.jpeg', upload_to='main_app/static/ava/'),
        ),
    ]
